#!/usr/bin/env python3
"""Assemble .pyi stub fragments from proc-macro output into trace_parser/_native.pyi.

This script:
1. Collects *.stub files from target/stubs/
2. Adds hand-written types (Trace, TracingMark)
3. Generates __init__.py, __init__.pyi, and _native.pyi
4. Runs ruff format
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

# ── Hand-written types (not generated by macros) ──────────────────────────

TRACE_STUB = """\
class Trace:
    thread_name: str
    thread_tid: int
    thread_tgid: int | None
    cpu: int
    flags: str
    timestamp: float
    event_name: str
    payload_raw: str
    def __init__(
        self,
        thread_name: str,
        thread_tid: int,
        thread_tgid: int | None,
        cpu: int,
        flags: str,
        timestamp: float,
        event_name: str,
        payload_raw: str,
    ) -> None: ...
    @staticmethod
    def can_be_parsed(line: str) -> bool: ...
    @staticmethod
    def parse(line: str) -> Trace | None: ...
    @property
    def timestamp_ms(self) -> float: ...
    @timestamp_ms.setter
    def timestamp_ms(self, value: float) -> None: ...
    @property
    def timestamp_ns(self) -> int: ...
    @timestamp_ns.setter
    def timestamp_ns(self, value: int) -> None: ...
    @property
    def payload(self) -> str: ...
    @property
    def template(self) -> str: ...
    def payload_to_string(self) -> str: ...
    def to_string(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __str__(self) -> str: ...
    def __copy__(self) -> Trace: ...
    def __deepcopy__(self, memo: object) -> Trace: ...
"""

TRACING_MARK_STUB = None  # Generated by macro, no manual stub needed


def collect_stubs(stubs_dir: Path) -> list[str]:
    """Collect all .stub files and sort them."""
    if not stubs_dir.exists():
        print(
            f"Warning: {stubs_dir} does not exist, run `cargo build` first",
            file=sys.stderr,
        )
        return []
    stubs = sorted(stubs_dir.glob("*.stub"))
    return [s.read_text() for s in stubs]


def extract_class_name(stub: str) -> str | None:
    m = re.match(r"class (\w+):", stub)
    return m.group(1) if m else None


def assemble_native_pyi(
    stubs: list[str],
    manual_stubs: dict[str, str],
) -> str:
    """Assemble _native.pyi from generated + manual stubs."""
    lines: list[str] = []
    lines.append('"""Type stubs for trace_parser._native native extension."""')
    lines.append("from __future__ import annotations")

    # Check if any stub uses typing.Any
    all_content = "\n".join(stubs) + "\n".join(manual_stubs.values())
    if "typing." in all_content:
        lines.append("import typing")
    lines.append("from typing_extensions import Self")
    lines.append("")

    # Hand-written first
    for name, stub in sorted(manual_stubs.items()):
        lines.append(stub)
        lines.append("")

    # Generated stubs
    for stub in stubs:
        lines.append(stub)
        lines.append("")

    # parse_trace, parse_trace_file, version
    lines.append("def parse_trace(line: str) -> Trace | None: ...")
    lines.append(
        "def parse_trace_file(path: str, filter_event: str | None = None) -> list[Trace]: ..."
    )
    lines.append("def version() -> str: ...")
    lines.append("")

    return "\n".join(lines)


def assemble_init_pyi(class_names: list[str]) -> str:
    """Generate __init__.pyi from class names."""
    imports = ",\n    ".join(
        sorted(class_names + ["parse_trace", "parse_trace_file", "version"])
    )
    all_items = ",\n    ".join(
        f'"{n}"'
        for n in sorted(class_names + ["parse_trace", "parse_trace_file", "version"])
    )

    return f"""\
from ._native import (
    {imports},
)

__all__ = (
    {all_items},
)
"""


def assemble_init_py(class_names: list[str]) -> str:
    """Generate __init__.py re-export from _native."""
    exports = sorted(class_names + ["parse_trace", "parse_trace_file", "version"])

    imports = "".join(f"    {name},\n" for name in exports)
    all_items = "".join(f'    "{name}",\n' for name in exports)

    return f'''\
"""trace_parser — fast ftrace/tracefs log parser."""

from trace_parser._native import (
{imports})

__all__ = (
{all_items})
'''


def run_ruff(paths: list[Path]) -> None:
    """Run ruff format on the given paths."""
    try:
        subprocess.run(
            [sys.executable, "-m", "ruff", "format"] + [str(p) for p in paths],
            check=True,
            capture_output=True,
            text=True,
        )
    except (subprocess.CalledProcessError, FileNotFoundError) as e:
        print(f"Warning: ruff format failed: {e}", file=sys.stderr)


def main() -> int:
    project_root = Path(__file__).resolve().parent.parent
    stubs_dir = project_root / "target" / "stubs"
    package_dir = project_root / "trace_parser"

    # Collect generated stubs
    generated = collect_stubs(stubs_dir)

    # Manual stubs (not generated by macros)
    manual: dict[str, str] = {
        "Trace": TRACE_STUB,
        # TracingMark is generated by macro (trace_event_class)
    }

    # Extract all class names
    class_names = list(manual.keys())
    for stub in generated:
        name = extract_class_name(stub)
        if name and name not in class_names:
            class_names.append(name)

    # Assemble files
    native_pyi = assemble_native_pyi(generated, manual)
    init_pyi = assemble_init_pyi(class_names)
    init_py = assemble_init_py(class_names)

    # Write files
    (package_dir / "_native.pyi").write_text(native_pyi)
    (package_dir / "__init__.pyi").write_text(init_pyi)
    (package_dir / "__init__.py").write_text(init_py)

    # Run ruff format
    run_ruff(
        [
            package_dir / "_native.pyi",
            package_dir / "__init__.pyi",
            package_dir / "__init__.py",
        ]
    )

    print(f"Generated stubs for {len(class_names)} classes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
