"""Type stubs for trace_parser._native native extension."""

class Trace:
    thread_name: str
    thread_thread_tid: int
    thread_thread_tgid: int
    cpu: int
    flags: str
    timestamp: float
    event_name: str
    payload_raw: str
    def __init__(self, thread_name: str, thread_thread_tid: int, thread_thread_tgid: int, cpu: int, flags: str, timestamp: float, event_name: str, payload_raw: str) -> None: ...
    @staticmethod
    def can_be_parsed(line: str) -> bool: ...
    @staticmethod
    def parse(line: str) -> Trace | None: ...
    @property
    def timestamp_ms(self) -> float: ...
    @timestamp_ms.setter
    def timestamp_ms(self, value: float) -> None: ...
    @property
    def timestamp_ns(self) -> int: ...
    @timestamp_ns.setter
    def timestamp_ns(self, value: int) -> None: ...
    @property
    def payload(self) -> str: ...
    @property
    def template(self) -> str: ...
    def payload_to_string(self) -> str: ...
    def to_string(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __str__(self) -> str: ...
    def __copy__(self) -> Trace: ...
    def __deepcopy__(self, memo: object) -> Trace: ...

class TraceSchedSwitch:
    thread_name: str
    thread_thread_tid: int
    thread_thread_tgid: int
    cpu: int
    flags: str
    timestamp: float
    event_name: str
    payload_raw: str
    prev_comm: str
    prev_pid: int
    prev_prio: int
    prev_state: str
    next_comm: str
    next_pid: int
    next_prio: int
    def __init__(self, thread_name: str, thread_thread_tid: int, thread_thread_tgid: int, cpu: int, flags: str, timestamp: float, event_name: str, payload_raw: str, prev_comm: str, prev_pid: int, prev_prio: int, prev_state: str, next_comm: str, next_pid: int, next_prio: int) -> None: ...
    @staticmethod
    def can_be_parsed(line: str) -> bool: ...
    @staticmethod
    def parse(line: str) -> TraceSchedSwitch | None: ...
    @property
    def payload(self) -> str: ...
    @property
    def template(self) -> str: ...
    def payload_to_string(self) -> str: ...
    def to_string(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __str__(self) -> str: ...
    def __copy__(self) -> TraceSchedSwitch: ...
    def __deepcopy__(self, memo: object) -> TraceSchedSwitch: ...

class TraceSchedWakeup:
    thread_name: str
    thread_thread_tid: int
    thread_thread_tgid: int
    cpu: int
    flags: str
    timestamp: float
    event_name: str
    payload_raw: str
    comm: str
    pid: int
    prio: int
    target_cpu: int
    reason: int | None
    def __init__(self, thread_name: str, thread_thread_tid: int, thread_thread_tgid: int, cpu: int, flags: str, timestamp: float, event_name: str, payload_raw: str, comm: str, pid: int, prio: int, target_cpu: int, reason: int | None) -> None: ...
    @staticmethod
    def can_be_parsed(line: str) -> bool: ...
    @staticmethod
    def parse(line: str) -> TraceSchedWakeup | None: ...
    @property
    def payload(self) -> str: ...
    @property
    def template(self) -> str: ...
    def payload_to_string(self) -> str: ...
    def to_string(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __str__(self) -> str: ...
    def __copy__(self) -> TraceSchedWakeup: ...
    def __deepcopy__(self, memo: object) -> TraceSchedWakeup: ...

class TraceSchedWakeupNew:
    thread_name: str
    thread_thread_tid: int
    thread_thread_tgid: int
    cpu: int
    flags: str
    timestamp: float
    event_name: str
    payload_raw: str
    comm: str
    pid: int
    prio: int
    target_cpu: int
    def __init__(self, thread_name: str, thread_thread_tid: int, thread_thread_tgid: int, cpu: int, flags: str, timestamp: float, event_name: str, payload_raw: str, comm: str, pid: int, prio: int, target_cpu: int) -> None: ...
    @staticmethod
    def can_be_parsed(line: str) -> bool: ...
    @staticmethod
    def parse(line: str) -> TraceSchedWakeupNew | None: ...
    @property
    def payload(self) -> str: ...
    @property
    def template(self) -> str: ...
    def payload_to_string(self) -> str: ...
    def to_string(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __str__(self) -> str: ...
    def __copy__(self) -> TraceSchedWakeupNew: ...
    def __deepcopy__(self, memo: object) -> TraceSchedWakeupNew: ...

class TraceSchedProcessExit:
    thread_name: str
    thread_thread_tid: int
    thread_thread_tgid: int
    cpu: int
    flags: str
    timestamp: float
    event_name: str
    payload_raw: str
    comm: str
    pid: int
    prio: int
    group_dead: bool
    def __init__(self, thread_name: str, thread_thread_tid: int, thread_thread_tgid: int, cpu: int, flags: str, timestamp: float, event_name: str, payload_raw: str, comm: str, pid: int, prio: int, group_dead: bool) -> None: ...
    @staticmethod
    def can_be_parsed(line: str) -> bool: ...
    @staticmethod
    def parse(line: str) -> TraceSchedProcessExit | None: ...
    @property
    def payload(self) -> str: ...
    @property
    def template(self) -> str: ...
    def payload_to_string(self) -> str: ...
    def to_string(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __str__(self) -> str: ...
    def __copy__(self) -> TraceSchedProcessExit: ...
    def __deepcopy__(self, memo: object) -> TraceSchedProcessExit: ...

class TraceExit:
    thread_name: str
    thread_thread_tid: int
    thread_thread_tgid: int
    cpu: int
    flags: str
    timestamp: float
    event_name: str
    pid: int
    comm: str
    exit_thread_thread_tgid: int
    def __init__(self, thread_name: str, thread_thread_tid: int, thread_thread_tgid: int, cpu: int, flags: str, timestamp: float, pid: int, comm: str, exit_thread_thread_tgid: int) -> None: ...
    @staticmethod
    def can_be_parsed(line: str) -> bool: ...
    @staticmethod
    def parse(line: str) -> TraceExit | None: ...
    @property
    def payload(self) -> str: ...
    @property
    def template(self) -> str: ...
    def to_string(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __str__(self) -> str: ...
    def __copy__(self) -> TraceExit: ...
    def __deepcopy__(self, memo: object) -> TraceExit: ...

class TraceCpuFrequency:
    thread_name: str
    thread_thread_tid: int
    thread_thread_tgid: int
    cpu: int
    flags: str
    timestamp: float
    event_name: str
    payload_raw: str
    state: int
    cpu_id: int
    def __init__(self, thread_name: str, thread_thread_tid: int, thread_thread_tgid: int, cpu: int, flags: str, timestamp: float, event_name: str, payload_raw: str, state: int, cpu_id: int) -> None: ...
    @staticmethod
    def can_be_parsed(line: str) -> bool: ...
    @staticmethod
    def parse(line: str) -> TraceCpuFrequency | None: ...
    @property
    def payload(self) -> str: ...
    @property
    def template(self) -> str: ...
    def payload_to_string(self) -> str: ...
    def to_string(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __str__(self) -> str: ...
    def __copy__(self) -> TraceCpuFrequency: ...
    def __deepcopy__(self, memo: object) -> TraceCpuFrequency: ...

class TraceDevFrequency:
    thread_name: str
    thread_thread_tid: int
    thread_thread_tgid: int
    cpu: int
    flags: str
    timestamp: float
    event_name: str
    payload_raw: str
    clk: str
    state: int
    cpu_id: int
    def __init__(self, thread_name: str, thread_thread_tid: int, thread_thread_tgid: int, cpu: int, flags: str, timestamp: float, event_name: str, payload_raw: str, clk: str, state: int, cpu_id: int) -> None: ...
    @staticmethod
    def can_be_parsed(line: str) -> bool: ...
    @staticmethod
    def parse(line: str) -> TraceDevFrequency | None: ...
    @property
    def payload(self) -> str: ...
    @property
    def template(self) -> str: ...
    def payload_to_string(self) -> str: ...
    def to_string(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __str__(self) -> str: ...
    def __copy__(self) -> TraceDevFrequency: ...
    def __deepcopy__(self, memo: object) -> TraceDevFrequency: ...

class TracingMark:
    thread_name: str
    thread_thread_tid: int
    thread_thread_tgid: int
    cpu: int
    flags: str
    timestamp: float
    event_name: str
    payload_raw: str
    def __init__(self, thread_name: str, thread_thread_tid: int, thread_thread_tgid: int, cpu: int, flags: str, timestamp: float, event_name: str, payload_raw: str) -> None: ...
    @staticmethod
    def can_be_parsed(line: str) -> bool: ...
    @staticmethod
    def parse(line: str) -> TracingMark | None: ...
    @property
    def payload(self) -> str: ...
    @property
    def template(self) -> str: ...
    def payload_to_string(self) -> str: ...
    def to_string(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __str__(self) -> str: ...
    def __copy__(self) -> TracingMark: ...
    def __deepcopy__(self, memo: object) -> TracingMark: ...

class TraceMarkBegin:
    thread_name: str
    thread_thread_tid: int
    thread_thread_tgid: int
    cpu: int
    flags: str
    timestamp: float
    event_name: str
    payload_raw: str
    trace_mark_thread_thread_tgid: int
    message: str
    def __init__(self, thread_name: str, thread_thread_tid: int, thread_thread_tgid: int, cpu: int, flags: str, timestamp: float, event_name: str, payload_raw: str, trace_mark_thread_thread_tgid: int, message: str) -> None: ...
    @staticmethod
    def can_be_parsed(line: str) -> bool: ...
    @staticmethod
    def parse(line: str) -> TraceMarkBegin | None: ...
    @property
    def payload(self) -> str: ...
    @property
    def template(self) -> str: ...
    def to_string(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __str__(self) -> str: ...
    def __copy__(self) -> TraceMarkBegin: ...
    def __deepcopy__(self, memo: object) -> TraceMarkBegin: ...

class TraceMarkEnd:
    thread_name: str
    thread_thread_tid: int
    thread_thread_tgid: int
    cpu: int
    flags: str
    timestamp: float
    event_name: str
    payload_raw: str
    trace_mark_thread_thread_tgid: int
    message: str
    def __init__(self, thread_name: str, thread_thread_tid: int, thread_thread_tgid: int, cpu: int, flags: str, timestamp: float, event_name: str, payload_raw: str, trace_mark_thread_thread_tgid: int, message: str) -> None: ...
    @staticmethod
    def can_be_parsed(line: str) -> bool: ...
    @staticmethod
    def parse(line: str) -> TraceMarkEnd | None: ...
    @property
    def payload(self) -> str: ...
    @property
    def template(self) -> str: ...
    def to_string(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __str__(self) -> str: ...
    def __copy__(self) -> TraceMarkEnd: ...
    def __deepcopy__(self, memo: object) -> TraceMarkEnd: ...

class TraceReceiveVsync:
    thread_name: str
    thread_thread_tid: int
    thread_thread_tgid: int
    cpu: int
    flags: str
    timestamp: float
    event_name: str
    trace_mark_thread_thread_tgid: int
    message: str
    frame_number: int
    def __init__(self, thread_name: str, thread_thread_tid: int, thread_thread_tgid: int, cpu: int, flags: str, timestamp: float, trace_mark_thread_thread_tgid: int, message: str, frame_number: int) -> None: ...
    @staticmethod
    def can_be_parsed(line: str) -> bool: ...
    @staticmethod
    def parse(line: str) -> TraceReceiveVsync | None: ...
    @property
    def payload(self) -> str: ...
    @property
    def template(self) -> str: ...
    def to_string(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __str__(self) -> str: ...
    def __copy__(self) -> TraceReceiveVsync: ...
    def __deepcopy__(self, memo: object) -> TraceReceiveVsync: ...

def parse_trace(line: str) -> Trace | None: ...
def parse_trace_file(path: str, filter_event: str | None = None) -> list[Trace]: ...
def version() -> str: ...
